### ISSUE TITLE
A question for thread solution

### ISSUE THREAD

**Issue by SYuPing** [ARMmbed/k64f-border-router#21]
I'm feeling sorry to leave message which is not about development issues here again, but I don't know where should I leave the question...

According to the Note( Note : this Border Router does not support Thread) which is on the third line in the preamble of these example, whether the thread example must use 6lowpan gateway router fot networking or not?

In other words, if it would added thread solution on k64f-border-router like this example in the future or it must need 6lowpan gateway router just coulde use thread for networking? 

Very thanks.

**Comment by mlnx** [comment]
This is a 6LoWPAN only Border Router. We will have a Thread BR in the future, probably on a different repository.
Please contact your ARM Partner Lead for more information.
