### ISSUE TITLE
Using the backhaul-driver (ethernet) for sending messages

### ISSUE THREAD

**Issue by tibmanus** [ARMmbed/k64f-border-router#25]
Is there any way to enable opening sockets in the border router application?
Now if I try this I get SOCKET_ERROR_BAD_STACK: "socket stack has incomplete API".

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2676

**Comment by SeppoTakalo** [comment]
Hi @tibmanus 
Than you for your question.

Actually for this version, the mbed-os Sockets do not work in border router. This is due the fact that the SAL (Socket Abstraction Layer) is not yet ported for the border router.

We will consider adding the support for the future releases.

Best Regards,
Seppo Takalo
