### ISSUE TITLE
K64-BR does not work with mbed OS Client example (mbed OS 5.0)

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/k64f-border-router#32]
The documentation on this k64f-border router refers to the [mbed Client example][https://github.com/ARMmbed/mbed-client-example-6lowpan] which is running mbed OS 3.0.

The documentation and configuration on this application has to be updated to make sure it works with the [mbed OS 5.0 Client example](https://github.com/ARMmbed/mbed-os-example-client) configured as *6LoWPAN*

@SeppoTakalo @hasnainvirk

**Comment by hasnainvirk** [comment]
It supports both mbed-os 3 and mbed-os 5. Yes, there was a mistake in the URL of the example application. Which is now fixed. New tag is also out (r4). For mbed-os 3 there is a seperate link.
