### ISSUE TITLE
Security Mode

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/k64f-border-router#34]
OOB I needed to remove this line:
```
"security-mode": "PSK",
```
from mbed_app.json for this example to work

**Comment by hasnainvirk** [comment]
Is this a valid issue @sarahmarshy ?
Did you read the following excerpt in https://github.com/ARMmbed/mbed-os-example-client ?
NOTE: If you are using k64f-border-router (which can be used only as a 6LoWPAN BR and only with FRDM-K64F), you need to enable another security feature. By default, k64f-border-router uses PSK as security. You can either enable security here on your mbed-os-example-client application, e.g.,

    "target_overrides": {
        "*": {
            "mbed-mesh-api.6lowpan-nd-security-mode": "PSK",
        }
    }

or you can remove link layer security from k64f-border-router. For doing that, change the mbed_app.json fetched from k64f-border-router repository, e.g.,

    "config": {
            "security-mode": "NONE",
        }

**Comment by hasnainvirk** [comment]
If not, then please close this issue.
