### ISSUE TITLE
Update mbed-os.lib when 5.2 release becomes available

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/k64f-border-router#35]

**Comment by hasnainvirk** [comment]
@MarceloSalazar Updated in https://github.com/ARMmbed/k64f-border-router/commit/603be404ef0ad2dfd83921ecb224195a32c37ee0

Please test and close the issue.

**Comment by MarceloSalazar** [comment]
Checked `mbed-os.lib` has been updated. Unable to test this soon.
