### ISSUE TITLE
Porting of k64f-border-router

### ISSUE THREAD

**Issue by betzw** [ARMmbed/k64f-border-router#39]
Has this border-router application ever been ported to some other platform than K64F, e.g. NUCLEO-F429ZI?

cc @screamerbg

**Comment by hasnainvirk** [comment]
@betzw No. As the name suggests, its a specific port to a particular platform. However, its nothing more than an application. Actual, border router logic resides in nanostack-border-router which is being used by this application. There are porting instructions on that repo. https://github.com/ARMmbed/nanostack-border-router
So anyone can port 6LOWPAN border router logic easily to any platform. This k64f-border-router application is just an example.

**Comment by hasnainvirk** [comment]
Closing this as it is not an issue.
