### ISSUE TITLE
6LoWPAN node unable to connect to this K64 BR

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/k64f-border-router#43]
Tested recent commit that includes mbed OS 5.3-rc3
SHA: 19233840b6521c2ae191396ebbb32ebcdd01a909

6LoWPAN node (from mesh-minimal example) is not able to connect to this K64 BR.
However, 6LoWPAN node works ok with mbed GW (firefly).

@SeppoTakalo please have a look

**Comment by SeppoTakalo** [comment]
Tested with `mesh-minimal` example.
By default, this example uses security mode `PSK` and the  mesh-minimal uses no security.

If you change this to use `NONE` or the mesh-minimal to use `PSK` it works.

**Comment by MarceloSalazar** [comment]
Thanks for the info. We need to update either the mesh-minimal example, or this K64 BR to work out of the box and remain compatible with each other.
Could you please make the changes?

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/k64f-border-router/tree/mbed-os-5.3.0-rc

Now default security mode is `NONE` so it match the mesh-minimal.

TODO: Needs documentation update for selecting security features.

**Comment by MarceloSalazar** [comment]
Thanks @SeppoTakalo 
I confirm it now works fine!
