### ISSUE TITLE
Need documentation on selecting security features.

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/k64f-border-router#44]
By default, security is `NONE`
Need a section in the doc to explain how to enable PSK and possibly other security configurations.

Issue identified here: https://github.com/ARMmbed/k64f-border-router/issues/43

**Comment by SeppoTakalo** [comment]
Actually, security features were briefly mentioned here: https://github.com/ARMmbed/nanostack-border-router#configuring-nanostack-border-router

But clearly a full overhaul is needed to make these documentations make it easier to spot such a information.

**Comment by adbridge** [comment]
ARM Internal Ref: ONME-2954

**Comment by SeppoTakalo** [comment]
Closing this as security features are in the docs linked and this is outdated repository.
