### ISSUE TITLE
support for thread

### ISSUE THREAD

**Issue by haishengliu** [ARMmbed/k64f-border-router#45]
Hello, 

As mentioned in readme.md, only 6lowpan supported  in this project, 
I am wondering if the support for thread will be considered in your next release?

thanks in advance

Haisheng

**Comment by TuomoHautamaki** [comment]
Hi @haishengliu 

Thank  you for your interest.
We have considered this but we cannot share our plans in public yet. We will close this ticket now but please follow-up the repository updates. 

Regards,
Tuomo
